name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: Select XCode
      run: sudo xcode-select -switch /Applications/Xcode.app

    - name: XCode version
      run: /usr/bin/xcodebuild -version
      
    - name: Run unit tests
      run: xcodebuild test -scheme TMDB -project TMDB.xcodeproj -destination 'platform=iOS Simulator,OS=14.0,name=iPhone 11 Pro Max' | xcpretty && exit ${PIPESTATUS[0]}
      
