name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build and Test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: Select XCode
      run: sudo xcode-select -switch /Applications/Xcode.app

    - name: XCode version
      run: /usr/bin/xcodebuild -version
    
    - name: Install Dependencies
      run: pod install --repo-update
      
    - name: Build
      run: xcodebuild clean build -scheme TMDB -workspace TMDB.xcworkspace -destination 'platform=iOS Simulator,OS=14.3,name=iPhone 12 Pro Max' | xcpretty && exit ${PIPESTATUS[0]}  
      
    - name: Run unit tests
      run: xcodebuild test -scheme TMDB -workspace TMDB.xcworkspace -destination 'platform=iOS Simulator,OS=14.3,name=iPhone 12 Pro Max' | xcpretty && exit ${PIPESTATUS[0]}
      
