name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install-dependencies:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select XCode
      run: sudo xcode-select -switch /Applications/Xcode.app
    
    - name: XCode version
      run: /usr/bin/xcodebuild -version

    - name: Install Dependencies
      run: pod install --repo-update

#     - name: Build
#       run: xcodebuild clean build -allowProvisioningUpdates -workspace TMDB.xcworkspace -scheme "TMDB"
      
  Test:
     runs-on: macOs-latest
     steps:
     - uses: actions/checkout@v2

     - name: Select XCode
       run: sudo xcode-select -switch /Applications/Xcode.app

     - name: XCode version
       run: /usr/bin/xcodebuild -version

     - name: Run unit tests
       run: xcodebuild test -scheme TMDB -project TMDB.xcodeproj -destination 'platform=iOS Simulator,id=B7212137-8D9C-4EE0-924C-2AC82BEED2E4,OS=14.3,name=iPhone 12 Pro Max' | xcpretty && exit ${PIPESTATUS[0]}
      
